function Hd = filter_test
%FILTER_TEST Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.6 and the Signal Processing Toolbox 6.9.
%
% Generated on: 15-Feb-2012 22:30:34
%

N     = 25;    % Order
Fpass = 0.45;  % Passband Frequency
Fstop = 0.55;  % Stopband Frequency

h = fdesign.lowpass('n,fp,fst', N, Fpass, Fstop);

Hd = design(h, 'equiripple', ...
    'StopbandShape', 'flat');



% [EOF]
